<a href="https://colab.research.google.com/github/MorvaridEmsaki/C2W-Telegram-Channel/blob/main/Thesis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



Import Libraries

In [23]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

import statsmodels.api as sm
import statsmodels.formula.api as smf

Load Dataset

In [24]:
from google.colab import files

uploaded = files.upload()

Saving Dataset 1_Posts.csv to Dataset 1_Posts (3).csv

In [25]:
df = pd.read_csv(next(iter(uploaded)))

In [26]:
df.head()

,id,date_tehran,time,Time Period,weekday_tehran,Weekday Number,text,views,forwards,Consultation Inquiries,...,Degree,Fund,QS_Rank,QS Available,Bachelor,Master,PhD,Post Doc,Month,Month Number
0,5.0,21-Nov-22,##############################################...,Morning,Monday,1.0,اولین و مهمترین قدم برای اخذ پذیرش تحصیلی داشت...,1123,7,0,...,Not Defined,0,NaN,0,0,0,0,0,November,11
1,6.0,21-Nov-22,##############################################...,Morning,Monday,1.0,NaN,1169,5,9,...,Not Defined,0,NaN,0,0,0,0,0,November,11
2,15.0,04-Dec-22,##############################################...,Night,Monday,1.0,📣 موقعیت تحصیلی 📣 مقطع: دکتری کشور: کانادا 🇨🇦...,1825,21,4,...,Not Defined,1,530.0,1,0,0,0,0,December,12
3,9.0,04-Dec-22,##############################################...,Night,Sunday,7.0,📣 موقعیت تحصیلی 📣 مقطع: دکتری کشور: انگلستان ...,1150,7,6,...,Not Defined,1,114.0,1,0,0,0,0,December,12
4,11.0,04-Dec-22,##############################################...,Night,Sunday,7.0,📣 موقعیت تحصیلی 📣 مقطع: دکتری کشور: آمریکا 🇺🇸...,1185,9,9,...,Not Defined,1,44.0,1,0,0,0,0,December,12

In [11]:
df.shape

(918, 23)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      918 non-null    float64
 1   date_tehran             918 non-null    object
 2   time                    918 non-null    object
 3   Time Period             918 non-null    object
 4   weekday_tehran          918 non-null    object
 5   Weekday Number          918 non-null    float64
 6   text                    909 non-null    object
 7   views                   918 non-null    int64
 8   forwards                918 non-null    int64
 9   Consultation Inquiries  918 non-null    int64
 10  has_media               918 non-null    int64
 11  media_type              918 non-null    object
 12  Country                 918 non-null    object
 13  Degree                  918 non-null    object
 14  Fund                    918 non-null    int64
 15  QS_Rank                 628 non-null    float64
 16  QS Available            918 non-null    int64
 17  Bachelor                918 non-null    int64
 18  Master                  918 non-null    int64
 19  PhD                     918 non-null    int64
 20  Post Doc                918 non-null    int64
 21  Month                   918 non-null    object
 22  Month Number            918 non-null    int64
dtypes: float64(3), int64(11), object(9)
memory usage: 165.1+ KB

In [13]:
df.isnull().sum()

id                          0
date_tehran                 0
time                        0
Time Period                 0
weekday_tehran              0
Weekday Number              0
text                        9
views                       0
forwards                    0
Consultation Inquiries      0
has_media                   0
media_type                  0
Country                     0
Degree                      0
Fund                        0
QS_Rank                   290
QS Available                0
Bachelor                    0
Master                      0
PhD                         0
Post Doc                    0
Month                       0
Month Number                0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.describe()

,id,Weekday Number,views,forwards,Consultation Inquiries,has_media,Fund,QS_Rank,QS Available,Bachelor,Master,PhD,Post Doc,Month Number
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,628.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,517.632898,3.802832,3428.391068,57.077342,9.995643,0.686275,0.606754,396.248408,0.684096,0.056645,0.173203,0.754902,0.027233,6.468410
std,287.566724,2.010689,1655.627996,64.030983,4.955195,0.464259,0.488737,407.027293,0.465128,0.231289,0.378629,0.430380,0.162851,4.369092
min,5.000000,1.000000,669.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,273.250000,2.000000,2276.000000,21.000000,6.000000,0.000000,0.000000,103.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000
50%,514.500000,4.000000,3181.000000,37.000000,10.000000,1.000000,1.000000,256.000000,1.000000,0.000000,0.000000,1.000000,0.000000,6.000000
75%,770.750000,6.000000,4068.750000,71.000000,13.000000,1.000000,1.000000,601.000000,1.000000,0.000000,0.000000,1.000000,0.000000,11.000000
max,1008.000000,7.000000,14626.000000,530.000000,22.000000,1.000000,1.000000,4000.000000,1.000000,1.000000,1.000000,1.000000,1.000000,12.000000

In [16]:
df["Country"].unique()

array(['Not Defined', 'Canada', 'United Kingdom', 'United States',
       'Sweden', 'Australia', 'Italy', 'Netherlands', 'Spain',
       'New Zealand', 'Denmark', 'Ireland', 'Germany', 'France', 'Japan',
       'Austria', 'Taiwan', 'Singapore', 'China', 'Turkey', 'Belgium',
       'Norway', 'Switzerland', 'Qatar', 'UAE', 'Malaysia', 'Romania',
       'South Korea', 'Poland', 'Hungary', 'Saudi Arabia', 'Finland',
       'Thailand'], dtype=object)

In [17]:
df["Degree"].unique()

array(['Not Defined', 'Bachelor', 'PhD', 'Postdoc', 'Bachelor; Master',
       'Postdoc; Bachelor; Master', 'Master; PhD',
       'Bachelor; Master; PhD', 'Master', 'Postdoc; Master'], dtype=object)

In [18]:
df["media_type"].unique()

array(['No Media', 'Photo', 'URL', 'Poll', 'Document'], dtype=object)

In [19]:
df["Month"].unique()

array(['November', 'December', 'January', 'February', 'March', 'April',
       'May', 'June', 'July', 'August', 'September', 'October'],
      dtype=object)

In [20]:
df["Country"].value_counts()

Country
United States     164
United Kingdom    137
Canada            118
Not Defined       115
Australia          74
Germany            62
Sweden             28
Netherlands        27
Ireland            21
Switzerland        18
Italy              17
France             16
New Zealand        15
Belgium            14
Taiwan             12
Austria            12
Denmark            11
Norway              8
Malaysia            6
Qatar               5
Spain               5
Romania             5
Turkey              5
China               5
Japan               4
Singapore           3
UAE                 2
South Korea         2
Saudi Arabia        2
Finland             2
Poland              1
Hungary             1
Thailand            1
Name: count, dtype: int64

In [21]:
df["media_type"].value_counts()

media_type
Photo       337
No Media    288
URL         281
Poll          7
Document      5
Name: count, dtype: int64

Variable Classification

In [27]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

df.columns.tolist()

['id',
 'date_tehran',
 'time',
 'time_period',
 'weekday_tehran',
 'weekday_number',
 'text',
 'views',
 'forwards',
 'consultation_inquiries',
 'has_media',
 'media_type',
 'country',
 'degree',
 'fund',
 'qs_rank',
 'qs_available',
 'bachelor',
 'master',
 'phd',
 'post_doc',
 'month',
 'month_number']

In [28]:
df.dtypes

id                        float64
date_tehran                object
time                       object
time_period                object
weekday_tehran             object
weekday_number            float64
text                       object
views                       int64
forwards                    int64
consultation_inquiries      int64
has_media                   int64
media_type                 object
country                    object
degree                     object
fund                        int64
qs_rank                   float64
qs_available                int64
bachelor                    int64
master                      int64
phd                         int64
post_doc                    int64
month                      object
month_number                int64
dtype: object

In [29]:
df["weekday_number"] = df["weekday_number"].astype(int)